### ISSUE TITLE
missing information about Installation (using Cocoapods)

### ISSUE THREAD

**Issue by AMiketta** [UPcload/FitAnalytics-WebWidget-iOS#13]
Hi,

it seems that there are some information about the cocoapod integration are missing. 
Text in  the Readme:
"Prerequisities:

XCode 7 or higher
iOS 8 or higher
Step 1. Make sure you already have cocoapods installed in your system. Otherwise you can follow the steps in cocoapods documentation to install https://cocoapods.org/

Step 2. To initialize the pod in your project use pod init command to create a Podfile with smart defaults.

Step 3. Now you can install the dependencies in your project by using pod install command.

Step 4. Make sure you always open Xcode Workspace instead of Xcode Project. You can do it by using open YourApp.xcworkspace command in terminal."

the name of the pod is missing and the source if it ist nor in cocoapods

**Comment by tjelen** [comment]
Should be published now at: https://github.com/CocoaPods/Specs/tree/master/Specs/1/c/7/FitAnalytics-WebWidget
